spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thgroupdb
    username: greenfarm
    password: greenfarm

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

checkMessageStatus:
  schedule: "0 0/1 * * * ?"  # Runs every minute
  maxRuns: 3                 # Maximum number of runs


